package com.kd.maindata.sys.message.model;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.id
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.title
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.subject
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_message.content
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.id
     *
     * @return the value of sys_message.id
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.id
     *
     * @param id the value for sys_message.id
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.title
     *
     * @return the value of sys_message.title
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.title
     *
     * @param title the value for sys_message.title
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.subject
     *
     * @return the value of sys_message.subject
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.subject
     *
     * @param subject the value for sys_message.subject
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_message.content
     *
     * @return the value of sys_message.content
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_message.content
     *
     * @param content the value for sys_message.content
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}