package com.kd.maindata.sys.message.dao;

import com.kd.maindata.sys.message.model.Message;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    Message selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_message
     *
     * @mbg.generated Sat Mar 18 22:12:31 CST 2017
     */
    int updateByPrimaryKey(Message record);
}